import "@/styles/globals.css";
import { Metadata, Viewport } from "next"; 
import clsx from "clsx";

import { Providers } from "./providers"; 

import { Alex_Brush, Montserrat } from 'next/font/google'

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";

const alexBrush = Alex_Brush({ 
  weight: ['400'],
  subsets: ['latin'] ,
  variable: '--font-alexBrush',
});


const montserrat = Montserrat({ 
  weight: ['100', '200','300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'] ,
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Music App',
  description: 'Generated by create next app'
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body
        className={clsx(
          "min-h-screen bg-pink-900/40 font-sans antialiased overflow-x-hidden relative",
          alexBrush.variable,
          montserrat.variable,
          
        )}
      >
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <div className="relative flex flex-col h-screen">  
            <main className="flex-grow ">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
